version: 2.1
jobs:
  build:
    macos:
      xcode: 26.3.0
    resource_class: m4pro.medium
    steps:
      - run:
          name: Checkout
          command: git clone https://github.com/bmkiefer/dotfiles.git .
      - run:
          name: Run Setup Script
          command: ./setup.sh
      - run:
          name: Verify Installed Tools
          command: |
            source ~/.bash_profile
            which nvim
            which nvm
            which node
            which tmux
            which lua
            which lua-language-server
            which uv
            which ruff
            which pyrefly
            which claude

