version: 2.1
jobs:
  build:
    macos:
      xcode: 26.3.0
    resource_class: m4pro.medium
    steps:
      - run:
          name: Checkout
          command: git clone https://github.com/bmkiefer/dotfiles.git .
      - run:
          name: Run Setup Script
          command: ./setup.sh

